using DEM.Net.Core.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SketchFab;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace SampleApp
{
    class SketchFabSample
    {
        private readonly ILogger _logger;
        private readonly SketchFabApi _sketchFabApi;
        private readonly string _sketchFabToken;

        public SketchFabSample(SketchFabApi sketchFabExport, ILogger<SketchFabSample> logger, IOptions<AppSecrets> secrets)
        {
            this._logger = logger;
            this._sketchFabApi = sketchFabExport;
            this._sketchFabToken = secrets.Value.SketchFabToken;

            if (string.IsNullOrEmpty(this._sketchFabToken))
            {
                _logger.LogWarning($"SketchFabToken is not set. Ensure you have a secrets.json file with a SketchFabToken entry with your api token (see https://sketchfab.com/settings/password)");
            }
        }

        public void Run()
        {

            List<Collection> collections = _sketchFabApi.GetMyCollectionsAsync(_sketchFabToken).GetAwaiter().GetResult();

            if (collections.Any(c => c.name == "Helladic Tests"))
            {

            }


            UploadModelRequest upload = new UploadModelRequest()
            {
                Description = "TEST",// * Generated by [DEM Net Elevation API](https://elevationapi.com)\n* Helladic test upload",
                FilePath = Path.Combine(Directory.GetCurrentDirectory(), "SketchFab", "C1410_OsmTopo.glb"),
                IsInspectable = true,
                IsPrivate = false,
                IsPublished = false,
                Name = "C1410_OsmTopo TEST",
                Options = new ModelOptions() { Background = SkecthFabEnvironment.Footprint_Court, Shading = ShadingType.lit }
            };


            var uuid = _sketchFabApi.UploadModelAsync(upload, _sketchFabToken).GetAwaiter().GetResult();
        }
    }
}
